version: 5.1.0
variant: default
logo:
  text: LXZ
navbar:
  menu:
    首页: /
    归档: /archives
    分类: /categories
    标签: /tags
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/lvxingzhi
    Email:
      icon: fas fa-envelope
      url: mailto:349024548@qq.com
footer:
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/lvxingzhi
    Email:
      icon: fas fa-envelope
      url: mailto:349024548@qq.com
article:
  highlight:
    theme: atom-one-dark
    clipboard: true
    fold: unfolded
  readtime: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/licenses/by-nc-sa/4.0/
search:
  type: insight
sidebar:
  left:
    sticky: false
  right:
    sticky: true
widgets:
  -
    position: left
    type: profile
    author: sunday
    author_title: hit the shops
    location: 
    avatar: /images/myhead.avif
    avatar_rounded: true
    gravatar:
    follow_link: https://github.com/lvxingzhi
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/lvxingzhi
      Email:
        icon: fas fa-envelope
        url: mailto:349024548@qq.com
  -
    position: left
    type: toc
    index: true
    collapsed: false
    depth: 3
  -
    position: left
    type: categories
  -
    position: left
    type: recent_posts
  -
    position: left
    type: archives
  -
    position: left
    type: tags
    order_by: name
    order: 1
    amount:
    show_count: true
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
  bing_webmaster:
  busuanzi: true
  cnzz:
  cookieconsent:
    type: info
    theme: edgeless
    static: false
  gallery: true
  google_analytics:
  hotjar:
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: fontawesome
head:
  favicon: /images/myhead.avif
